version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3005"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file watching
    command: npm run dev  # Or whatever your dev command is
