apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
      annotations:
        # If ConfigMaps change, roll pods
        checksum/nginx: {{ include (print $.Template.BasePath "/configmap-nginx.yaml") . | sha256sum }}
        {{- if .Values.runtimeConfig.enabled }}
        checksum/app-config: {{ include (print $.Template.BasePath "/configmap-runtime-config.yaml") . | sha256sum }}
        {{- end }}
    spec:
      serviceAccountName: {{ default (include "frontend.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.nginx.basePath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.nginx.basePath }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            {{- if .Values.runtimeConfig.enabled }}
            - name: app-config
              mountPath: /etc/nginx/app-config/app-config.js
              subPath: app-config.js
              readOnly: true
            {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "frontend.fullname" . }}-nginx
        {{- if .Values.runtimeConfig.enabled }}
        - name: app-config
          configMap:
            name: {{ include "frontend.fullname" . }}-app-config
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
